In [1]:
import EDRs_pkg.Root as root
import EDRs_pkg.Data as data
import EDRs_pkg.Fitting as ft

In [2]:
Root = root.System()
Root.setDataDir("/Users/liontea/Library/CloudStorage/OneDrive-SNU/연구데이터/MRCP_data/data_process/data_source/data/sonde/")
Root.getDataDir()
filePath = Root.getDataDir()

In [3]:
# Load code results
G4Data = data.MonteCarloData(filePath = filePath, codeType = "geant4")
G4Data.readData()

M6Data = data.MonteCarloData(filePath = filePath, codeType = "mcnp6")
M6Data.readData(isCombined=False)

PHITSData = data.MonteCarloData(filePath = filePath, codeType = "phits")
PHITSData.readData(isCombined=False)

Root.addCodeData(G4Data, M6Data, PHITSData)

In [4]:
# set position List 
positionList = [100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 7, 5, 3, 0, -10, -20, \
    -30, -40, -50, -60, -70, -80, -90, -100, -110, -120, -130, -140, -150]
postureList = ["op", "sp", "sq", "bd"]
Root.setPositionList(positionList)
Root.setPostureList(postureList)

In [5]:
# Load Tissue weighting factor data
fTWFPath = "/Users/liontea/Library/CloudStorage/OneDrive-SNU/연구데이터/MRCP_data/data_process/data_source/load_data/eff_tissue_IDs.inp"
TWF = data.SupplementaryData(filePath = fTWFPath, codeType = "TWF")

/Users/liontea/Library/CloudStorage/OneDrive-SNU/연구데이터/MRCP_data/data_process/data_source/load_data/eff_tissue_IDs.inp


In [6]:
Root.addSupplementalData(TWF)

In [7]:
Root.calcEffectiveDose()
# Root.writeEffDose()
# Root.writeOrganEffDose()
Root.computeEDR()
Root.computeOrganEDR()

/Users/liontea/miniconda3/envs/data_process/lib/python3.9/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [8]:
# a = G4Data.getDF_EDRs("op")
# b = G4Data.getDF_OrganContr("op")

# a = PHITSData.getDF_EDRs("op")
# b = PHITSData.getDF_OrganContr("op")

In [9]:
import numpy as np
# Plotting
fImagePath = "/Users/liontea/Library/CloudStorage/OneDrive-SNU/연구데이터/MRCP_data/data_process/images/sonde"
# Root.init_plot(imageFolderPath = fImagePath)
# Root.drawBasicFigures()

# G4Data.init_plot(imageFolderPath= fImagePath)
# G4Data.drawBasicFigures()
# G4Data.drawErrorBar(posture="OP", yscale = "log", isSave = False)
# G4Data.saveFig(position="Total")

# M6Data.setX(M6Data.getX())
# M6Data.setY(M6Data.getY())
# M6Data.setYError(M6Data.getYErr())
# M6Data.init_plot(imageFolderPath= fImagePath)
# M6Data.drawErrorBar(posture="SQ", yscale = "log", isSave = False)

# PHITSData.init_plot(imageFolderPath= fImagePath)
# PHITSData.drawErrorBar(posture="OP", yscale = "log", isSave = False)

In [10]:
# Root.drawCombinedFigures()

In [11]:
fitTool = ft.Fitting()
fitTool.addData(G4Data, M6Data, PHITSData)

In [12]:
fitTool.interpolate()

op GEANT4
6.113562548455081e-07 -2.6916116808964558e-05 0.0007190800405761557 0.03555861068894492 	 R^2:  0.9999251288503896
op MCNP6
1.2331613739913168e-07 3.2105200404961464e-05 -0.0009103392213837315 0.039692852357001554 	 R^2:  0.9993292250824539
op PHITS
2.892424990477779e-07 4.040123747341941e-06 0.00027069407615740046 0.025192910832688518 	 R^2:  0.9998576938792313
sp GEANT4
-3.8027110520890576e-08 5.120144630849097e-06 0.00043514155998035636 0.05649301572743136 	 R^2:  0.9994457455619563
sp MCNP6
-1.184317254558763e-09 6.449477156232188e-07 0.00039942025461256426 0.04399088224924389 	 R^2:  0.9941603165381667
sp PHITS
-2.2795645715528194e-08 4.0038562862068615e-06 0.00022612480922922678 0.04294229358773674 	 R^2:  0.9990494479158726
sq GEANT4
-2.2103695004823863e-07 4.192176725568224e-05 -5.926337600804739e-05 0.17565676337420535 	 R^2:  0.9999943143060583
bd GEANT4
5.977215603031598e-07 -2.9029029195758244e-05 0.0011750707634744454 0.07846568468361236 	 R^2:  0.999988294566923

In [13]:
Root.exportCoef(fitTool)

In [15]:
G4Data.fCoef["op"]

{'ground': (array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10]),
  array([0.4482964 , 0.33049451, 0.23395604, 0.16242932, 0.11282904,
         0.08148359, 0.05983437, 0.05030839, 0.04429071, 0.04023992]),
  array([0.00145347, 0.00120591, 0.00090843, 0.00069045, 0.00056599,
         0.00064173, 0.00039079, 0.00036137, 0.00033796, 0.00030665]),
  array([ 6.11356255e-07, -2.69161168e-05,  7.19080041e-04,  3.55586107e-02]),
  0.9999251288503896),
 'under': (array([  10,    7,    5,    3,    0,  -10,  -20,  -30,  -40,  -50,  -60,
          -70,  -80,  -90, -100, -110, -120, -130, -140, -150]),
  array([4.02399244e-02, 3.90038210e-02, 3.69284820e-02, 3.69264750e-02,
         2.90959848e-02, 3.15848414e-02, 1.63288783e-02, 8.60093772e-03,
         5.29811567e-03, 3.11953364e-03, 1.85182274e-03, 1.02656203e-03,
         5.57298267e-04, 3.09233467e-04, 2.07709591e-04, 9.02388568e-05,
         4.82653250e-05, 3.12148663e-05, 1.20797793e-05, 6.37235946e-06]),
  array([3.06649471e-04, 9.4202